using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using Models;

namespace Controllers
{
    class ControllerTestData
    // Skrevet af Jonas og Alex
    {
        static int kvmPris = 15000;
        static int antalHusejer = 50;
        static int antalMægler = 10;

        static List<int> postnumre = new List<int> {7100, 7120};
        static List<int> prisNedsætelser = new List<int> {0, 0, 50000, 100000, 150000};
        static List<string> energimærker = new List<string> {"F", "E", "D", "C", "B", "A", "A10", "A20"};
        static List<string> vejnavne = new List<string> {
            "Abelones Plads",
            "Abildstræde",
            "Abildvej",
            "Absalonsvej",
            "A C Møllersvej",
            "A C Pedersens Vej",
            "Adonisvej",
            "Agersbølparken",
            "Agersbølvej",
            "Agersnapsvej",
            "Agertoftevej",
            "Ahornvej",
            "Aldebertsmindevej",
            "Alleen",
            "Amalielunden",
            "Ammitsbølvej",
            "Anchersvej",
            "Andkærvej",
            "Andreas Nielsens Vej",
            "Anemonevej",
            "Antilopevej",
            "Anton Berntsensvej",
            "Apollovej",
            "Arne Poulsens Vej",
            "Artvej",
            "Askestræde",
            "Askevej",
            "Askevænget",
            "Atlasvej",
            "Badevænget",
            "Bagsnoge",
            "Bakkedraget",
            "Bakkeglimt",
            "Bakkekammen",
            "Bakkekrogen",
            "Bakkelyparken",
            "Bakkelyst",
            "Bakkevej",
            "Bakkevænget",
            "Banegårdspladsen",
            "Banestien",
            "Banevang",
            "Bangsalle",
            "Bardenflethsgade",
            "Baunevej",
            "Baunholtvej",
            "Bavnbjergvej",
            "Bechgaardsvej",
            "Bellevuevej",
            "Bellisvej",
            "Beriderbakken",
            "Bertel Nielsens Vej",
            "Betty Sørensen Parken",
            "Bindeleddet",
            "Birke Allé",
            "Birkemosen",
            "Birkene",
            "Birkestien",
            "Birkevej",
            "Birkevænget",
            "Bjørnekærvej",
            "Blegbanken",
            "Bleggaardsgade",
            "Blichersvej",
            "Blomstervænget",
            "Blåbærvej",
            "Boeskærvej",
            "Bogfinkevej",
            "Bolundsvej",
            "Bommerhavevej",
            "Borchs Alle",
            "Borgm Madsens Gade",
            "Borgvej",
            "Borgvold",
            "Boråsvej",
            "Boulevarden",
            "Brandbjergvej",
            "Brinckersvej",
            "Broagervej",
            "Brorsonsvej",
            "Brummersvej",
            "Brundalen",
            "Brunhøj",
            "Brunmose",
            "Bruns Allé",
            "Brynet",
            "Buchsvej",
            "Buen",
            "Bugattivej",
            "Buldalen",
            "Bygden",
            "Bygvænget",
            "Bymarken",
            "Bævervej",
            "Bødkervej",
            "Bøgeagervej",
            "Bøgelund",
            "Bøgeparken",
            "Bøgetoft",
            "Bøgevang",
            "Bøgevej",
            "Bøgomvej",
            "Centerbakken",
            "Ceresvej",
            "Chr Hansensvej",
            "Christiansminde",
            "Chr Jensens Vej",
            "Chr Winthersvej",
            "Citadelvej",
            "Dalgade",
            "Dalgasvej",
            "Dalglimt",
            "Dalvej",
            "Damgårdshaven",
            "Damhaven",
            "Damhusvej",
            "Dammen",
            "Danasvej",
            "Dandyvej",
            "Danmarksgade",
            "Degnevænget",
            "Den Hvide Facet",
            "Dianavej",
            "Dieselvej",
            "Diget",
            "Dildvej",
            "Diskovej",
            "Djævlekløftvej",
            "Dofovej",
            "Dolleriesvej",
            "Dornsvej",
            "Dronning Dagmars Vej",
            "Drosselvej",
            "Dtc Torvet",
            "Duevej",
            "Dunavej",
            "Dupontsvej",
            "Dusgårdvej",
            "Dybbølvej",
            "Dyrskuevej",
            "Dæmningen",
            "Edisonvej",
            "Egelundvej",
            "Egely Alle",
            "Egernvej",
            "Egevang",
            "Egevej",
            "Egevænget",
            "Ellehammersvej",
            "Ellensvej",
            "Ellestræde",
            "Ellevang",
            "Elmebakken",
            "Elmegårdsvej",
            "Elmevej",
            "Elsdyrvej",
            "Elvirasvej",
            "Emil Reesens Vej",
            "Enebærvej",
            "Engbakken",
            "Engdalsbakken",
            "Engelgårdsvej",
            "Enggade",
            "Enggaardsvej",
            "Enghaven",
            "Enghavevej",
            "Englandsvej",
            "Engmarksvej",
            "Engtoftevej",
            "Engvang",
            "Engvasen",
            "Engvej",
            "Erantisvej",
            "Erik Eriksens Vej",
            "Erosvej",
            "Esbern Snares Vej",
            "Eskholtvænget",
            "Eskimovej",
            "E T Jørgensens Vej",
            "Fabersvej",
            "Falkevej",
            "Falstersgade",
            "Fasanstien",
            "Ferrarivej",
            "Fertinvej",
            "Fidalvej",
            "Filippavej",
            "Finlandsvej",
            "Firehusevej",
            "Fisken",
            "Fiskergade",
            "Fjeldvigs Alle",
            "Fjellegade",
            "Fjordgade",
            "Fjordglimt",
            "Fjordmarken",
            "Flegborg",
            "Flegmade",
            "Florasvej",
            "Fløjstrupvej",
            "Foldegade",
            "Foran Møllen",
            "Fousbjergvej",
            "Fredens Allé",
            "Fredensgade",
            "Fredericiagade",
            "Fredericiavej",
            "Frederik Jensensvej",
            "Frederikshøjvej",
            "Frejasgade",
            "Fridtjof Nansensvej",
            "Friis Hansens Vej",
            "Frostvej",
            "Frøkær Skovvej",
            "Fuglevej",
            "Fundersvej",
            "Fyensgade",
            "Fyrreparken",
            "Fyrrestien",
            "Fyrretoften",
            "Gaiavej",
            "Galaksen",
            "Gammelhavn",
            "Gammelmarksvej",
            "Gammel Sving",
            "Gartnervænget",
            "Gemmavej",
            "Gimlevej",
            "Glambjerg Allé",
            "Glentestien",
            "Glentevej",
            "Gl Hornstrupvej",
            "Gl Højenvej",
            "Gl Jellingvej",
            "Gl Kolding Landevej",
            "Gl Kongevej",
            "Gl Landevej",
            "Gl Ribevej",
            "Gl Skibetvej",
            "Gl Smedevej",
            "Gludsmindevej",
            "Gl Viborgvej",
            "Gl. Vingstedvej",
            "Godthåbsvej",
            "Gormsgade",
            "Grantoften",
            "Grejs Bakke",
            "Grejsbjergvej",
            "Grejsdalsparken",
            "Grejsdalsvej",
            "Grejsdals Vænge",
            "Grejsvej",
            "Grejsåvænget",
            "Grenen",
            "Grundet Bakke",
            "Grundet Bygade",
            "Grundet Ringvej",
            "Grundtvigsvej",
            "Græsmarken",
            "Græsvænget",
            "Grønbækvej",
            "Grønholt",
            "Grønlandsvej",
            "Grønnedalen",
            "Grønnegade",
            "Grønningen",
            "Grønvang",
            "Grønvænget",
            "Gulerodsstien",
            "Gulkrog",
            "Gulkrogpladsen",
            "Gunhilds Plads",
            "Gunnbjørns Vej",
            "Gyvelvej",
            "Haderslevvej",
            "Hans Bundgaards Vej",
            "Hans Egedesvej",
            "Hans Rosendals Allé",
            "Haraldsgade",
            "Haraldsvænget",
            "Harevænget",
            "Hartmannsvej",
            "Hasselstræde",
            "Hasselvænget",
            "Havelodden",
            "Havesangervej",
            "Havnegade",
            "Havneparken",
            "Havnepladsen",
            "Havneøen",
            "Havrebakken",
            "H C Hansens Vej",
            "H C Lumbyes Vej",
            "Heibergsvej",
            "Heisesvej",
            "Hejrevej",
            "Helgesvej",
            "Heliosvej",
            "Helligkildevej",
            "Hellumvej",
            "Helsebakken",
            "Helsingørvej",
            "Hermelinvej",
            "Hermesvej",
            "Herredsvej",
            "Herslebsgade",
            "Hesselager",
            "Hesselballevej",
            "Hesselbjerg",
            "Hesselhøj",
            "Hesselkrog",
            "Hesselkær",
            "Hesseltoft",
            "Hesselvang",
            "Hestehave",
            "Hesteskoen",
            "Hf. Grundet",
            "Hf. Kongens Kær",
            "Hf. Mølholmsdalen",
            "Hjortevej",
            "Hjulmagervej",
            "Holger Danskes Vej",
            "Holger Sørensensvej",
            "Holmen",
            "Holmevej",
            "Holmshavevej",
            "Holtumvej",
            "Hopballevej",
            "Hornemansvej",
            "Horsensvej",
            "Horskær Mosevej",
            "Horskærvænget",
            "Horstedvej",
            "Hostrupsvej",
            "Hover Kirkevej",
            "Hovertoften",
            "Hovervej",
            "Hovgårdsvej",
            "Hulvejen",
            "Humlestien",
            "Hummelkærsvej",
            "Husumvej",
            "Hyldevej",
            "Hægestræde",
            "Høegh Hagensvej",
            "Høgestien",
            "Høgevej",
            "Høgsholtvej",
            "Højagervej",
            "Højbanetorvet",
            "Højbovej",
            "Højen Kirkevej",
            "Højen Skovvej",
            "Højen Tang",
            "Højenvej",
            "Højgårdvej",
            "Højløkkevej",
            "Højmarken",
            "Højskolevej",
            "Højtoft",
            "Højtoftevej",
            "Højvang",
            "Højvangvej",
            "Høllund Tværvej",
            "Høllundvej",
            "Hørmøllevej",
            "Ibæk Strandvej",
            "Ibækvej",
            "Ilderkærvej",
            "Ingemannsvej",
            "Ingvard Andersensvej",
            "Irisvej",
            "Isabellahøj",
            "Islandsvej",
            "Iver Jarls Vej",
            "Jacob Gades Stræde",
            "Jacobsmindevej",
            "Jagtvej",
            "Jakob Knudsens Vej",
            "Jellingvej",
            "Jenlevej",
            "Jennumvej",
            "Jens Grøns Vej",
            "Jens Ravns Vej",
            "Jeppe Jensensgade",
            "Jerlev Boulevard",
            "Jerlevgårdvej",
            "Jerlev Hedevej",
            "Jerlev Landevej",
            "Jerlevvej",
            "Jernbanegade",
            "Jernvej",
            "Johannesgade",
            "Jomfru Ingefreds Vej",
            "Jordbærstien",
            "Julius Jepsens Vej",
            "Julius Thomsensvej",
            "Junker Stranges Vej",
            "Junovej",
            "Jupitervej",
            "Jyllandsgade",
            "Jædersbæk",
            "Jægervænget",
            "Jørgen Brønlundsvej",
            "Jørgen Sørensensvej",
            "Kabbeltoft",
            "Kahytten",
            "Kaj Munks Vej",
            "Kalkbrænderivej",
            "Kammasvej",
            "Kappelagervej",
            "Karen Blixens Vej",
            "Karensdalvej",
            "Karetmagervej",
            "Karl Buchvænget",
            "Karsevej",
            "Kastanievej",
            "Keglebakken",
            "Keglekærvej",
            "Kiddesvej",
            "Kikkenborg",
            "Kildevang",
            "Kildevældsvej",
            "Kingosvej",
            "Kirkebyvej",
            "Kirkegade",
            "Kirkestien",
            "Kirketorvet",
            "Kirsebærstræde",
            "Kirsebærvej",
            "Kirsten Piils Vej",
            "Kjeld Abellsvej",
            "Kjærmarksvej",
            "Kjærsgaarden",
            "Klintevej",
            "Klostergade",
            "Kløvermarken",
            "Kløvermarksvej",
            "Kløvertoften",
            "Kløvervej",
            "Knabberupvej",
            "Knud Højgaards Vej",
            "Knud Rasmussensvej",
            "Knudsgade",
            "Knuth Beckers Vej",
            "Kobbelvænget",
            "Kofodsvej",
            "Koldingvej",
            "Kong Hans Vej",
            "Kongsvej",
            "Korntoften",
            "Korsdalsvej",
            "Korshave",
            "Kragelund Skovvej",
            "Krathave",
            "Krebsen",
            "Kringelhusvej",
            "Kristian Skous Vej",
            "Krogagervej",
            "Krogen",
            "Krogsmindevej",
            "Krohaven",
            "Krusemyntevej",
            "Kvak Mølle Vej",
            "Kærbøllinghusevej",
            "Kærmindevej",
            "Kærvej",
            "Ladegårdsvej",
            "Lanciavej",
            "Landlystvej",
            "Langelinie",
            "Langemarksvej",
            "Lange-Müllers Vej",
            "Laubsvej",
            "Ledavej",
            "Leragervej",
            "Lerbæk Møllevej",
            "Lerbækvej",
            "Lerbæk Vestre Skovvej",
            "Lerbæk Østre Skovvej",
            "Lertoften",
            "Liden Gunvers Vej",
            "Lido Alle",
            "Lien",
            "Liljevej",
            "Lille Bjerggade",
            "Lille Grundet Hulvej",
            "Lillegårdsvej",
            "Lille Mølkær",
            "Lindagerparken",
            "Lindealle",
            "Lindestræde",
            "Lindevej",
            "Lindevænget",
            "Lindved Tværvej",
            "Linnemannsgade",
            "Linnet Skovvej",
            "Linnetvej",
            "Logistikvej",
            "Lohsevej",
            "Lollandsgade",
            "Lomholtvej",
            "Lundahl Nielsens Vej",
            "Lundevej",
            "Lundhusvej",
            "Lundtoftevej",
            "Lupinvej",
            "Lyngbakken",
            "Lysholt Allé",
            "Lysholtvej",
            "Lærkestien",
            "Lærketoften",
            "Lærkevej",
            "Lærkevænget",
            "Lævej",
            "Løget Center",
            "Løget Dam",
            "Løget Høj",
            "Løgitmark",
            "Løjpen",
            "Løngangen",
            "Lønnestræde",
            "Løversysselvej",
            "Løvsangerstien",
            "Løvsangervej",
            "Magnoliavej",
            "Margrethevej",
            "Maribovej",
            "Marie Grubbes Vej",
            "Markvang",
            "Marsvej",
            "Maserativej",
            "Medeavej",
            "Mejsestien",
            "Mejsevej",
            "Mejsling Skovvej",
            "Mejslingvej",
            "Merianvej",
            "Merkurvej",
            "Mettelundvej",
            "Mindegade",
            "Mindevej",
            "Minervavej",
            "Mirabelstræde",
            "Miravej",
            "Moldevej",
            "Moselunden",
            "Mosen",
            "Mosevej",
            "Mosevænget",
            "Munkebjergvej",
            "Munkevej",
            "Musvitvej",
            "Musvågestien",
            "Mylius Erichsensvej",
            "Mysundevej",
            "Møgelholt",
            "Mølholm Landevej",
            "Mølholmvej",
            "Mølkærparken",
            "Mølkærvej",
            "Mølleager",
            "Møllebyvej",
            "Møllegade",
            "Møllehusvej",
            "Mølleparken",
            "Møller Jensensvej",
            "Møllestien",
            "Møllevej",
            "Møllevænget",
            "Mørkedalsvej",
            "Mågevej",
            "Naurstræde",
            "Navervej",
            "Neptunvej",
            "Niels Bentzens Alle",
            "Niels Bisteds Vej",
            "Niels Bohrs Vej",
            "Niels Bugges Vej",
            "Niels Ebbesens Vej",
            "Niels Finsensvej",
            "Niels Juels Vej",
            "Niels Kjeldsensvej",
            "Niels Pedersens Vej",
            "Niels Skousvej",
            "Niels W Gades Vej",
            "Nobilisvej",
            "Noersvej",
            "Nordbanen",
            "Nordkajen",
            "Nordlandsvej",
            "Nordlyvej",
            "Nordre Villavej",
            "Nordvej",
            "Nordås",
            "Norgesvej",
            "Novavej",
            "Nutzhornsgade",
            "Ny Agersbølvej",
            "Nyboesgade",
            "Nyborgvej",
            "Ny Grejsdalsvej",
            "Nygårdsvej",
            "Ny Hornstrupvej",
            "Nymarksvej",
            "Ny Solskovvej",
            "Nytoft",
            "Nyvej",
            "Nøddevænget",
            "Nørbjergvej",
            "Nørre Alle",
            "Nørrebjerget",
            "Nørrebrogade",
            "Nørre Bygade",
            "Nørrediget",
            "Nørregade",
            "Nørre Have",
            "Nørrekær",
            "Nørremark Center",
            "Nørremarksvej",
            "Nørreskov Huse",
            "Nørretorv",
            "Nørrevænget",
            "Obkærvej",
            "Odinsgade",
            "Oksviggårdsvej",
            "Olaf Ryesvej",
            "Ole Rømersvej",
            "Olgas Vej",
            "Orionvej",
            "Orla Lehmannsgade",
            "Otte Ruds Vej",
            "Ouskær",
            "Pakhusgade",
            "Pallasvej",
            "Pandoravej",
            "Paradis Allé",
            "Parallelvej",
            "Parkvej",
            "Passagen",
            "Peder Borchs Vej",
            "Pedersholms Allé",
            "Persillestien",
            "Peter Freuchensvej",
            "Petershøjvej",
            "Petersmindevej",
            "Pilevænget",
            "Platan Alle",
            "Platzvej",
            "Plutovej",
            "Polarvej",
            "Pomonavej",
            "Poppelvej",
            "Porrestien",
            "Porschevej",
            "Pottemagervej",
            "Primulavej",
            "Prins Buris Vej",
            "Præstebakken",
            "Præstegyde",
            "Præstegårdsvej",
            "Ravnsbækvej",
            "Reinholdts Plads",
            "Rensdyrvej",
            "Ribegade",
            "Ribe Landevej",
            "Riberlundvej",
            "Ribevej",
            "Ridder Stigs Vej",
            "Ringdams Kobbel",
            "Roarsvej",
            "Rolighedsvej",
            "Rommes Ager",
            "Rommesvej",
            "Romsgaardsvej",
            "Roms Hule",
            "Rosengårds Alle",
            "Rosenvej",
            "Roskildevej",
            "Rosmarinvej",
            "Rubjergvej",
            "Rued Langgaards Vej",
            "Ruevej",
            "Rugbakken",
            "Rugballevej",
            "Rugsted Tværvej",
            "Rugstedvej",
            "Rugsted Vestvej",
            "Rugvænget",
            "Rungsvej",
            "Rusen",
            "Ryttervej",
            "Rødkildevej",
            "Rønnestræde",
            "Rønshovedvej",
            "Rønsled",
            "Rønsvej",
            "Rørhaven",
            "Rørsangervej",
            "Rådhuspassagen",
            "Rådhustorvet",
            "Raadyrvej",
            "Raakjærsvej",
            "Sadelmagervej",
            "Sandagervej",
            "Sandhøjen",
            "Sandnæsvej",
            "Sandtoften",
            "Sankelmarkvej",
            "Saturnvej",
            "Sdr. Tværkaj",
            "Sdr Vang",
            "Sdr Villavej",
            "Selleristien",
            "Signesvej",
            "Sikavej",
            "Silkehalevej",
            "Sindballevej",
            "Sindbjerglundvej",
            "Siriusvej",
            "Sjællandsgade",
            "Skakvej",
            "Skanderborgvej",
            "Skansen",
            "Skibet Bakkevej",
            "Skibetvej",
            "Skibsbroen",
            "Skipperstien",
            "Skjoldborgvej",
            "Skjoldsgade",
            "Skolegade",
            "Skomagervej",
            "Skorpionen",
            "Skov Allé",
            "Skovbakken",
            "Skovdallundvej",
            "Skovgade",
            "Skovglimt",
            "Skovgaardsvej",
            "Skovhøjen",
            "Skovkrogen",
            "Skovlyvej",
            "Skovmøllevej",
            "Skovparken",
            "Skovtoften",
            "Skovvang",
            "Skovvejen",
            "Skovvænget",
            "Skrædderbakken",
            "Skrædderstien",
            "Skyttehusgade",
            "Skyttehusvejen",
            "Skytten",
            "Skyttestien",
            "Skøn Valborgs Vej",
            "Sleldeparken",
            "Sleldevej",
            "Slots Alle",
            "Slotshusevej",
            "Slugten",
            "Slørvingevej",
            "Smalle Jerlevvej",
            "Smalle Vorkvej",
            "Smaragdvej",
            "Smedevej",
            "Smørhullet",
            "Snerlevej",
            "Sofievej",
            "Sognegårdsvej",
            "Solbakken",
            "Soldalen",
            "Solgave Alle",
            "Solkilde Alle",
            "Solkærvej",
            "Solsikkevej",
            "Solskovvej",
            "Solsortestien",
            "Solsortevej",
            "Solvang",
            "Spinderigade",
            "Spurvestien",
            "Spurvevej",
            "Spættevej",
            "Stadion Alle",
            "Staldgaardsgade",
            "Stampesvej",
            "St Bjerggade",
            "Steensens Vej",
            "Stenagervej",
            "Stenagervænget",
            "Stenbukken",
            "Stenhoved",
            "Stenhøjen",
            "Stenkisten",
            "Stentoften",
            "St. Grundet Skovvej",
            "Stien",
            "Stiftsvej",
            "Stjernevej",
            "Store Grundet Alle",
            "Storegårdsvej",
            "Storhaven",
            "Stormgade",
            "Strandgade",
            "Stubdrup Kirkevej",
            "Stubdrupvej",
            "Stævnen",
            "Stønnekærvej",
            "Stålvej",
            "Sukkertoppen",
            "Svajebassinet",
            "Svalevej",
            "Svanholmsgade",
            "Svend Dyrings Vej",
            "Svendsgade",
            "Sverigesvej",
            "Svinget",
            "Svinholtgårdvej",
            "Svinholt Skov Vej",
            "Svinholtvej",
            "Syden",
            "Sydkajen",
            "Syrenvej",
            "Sysselvej",
            "Sæteren",
            "Søager",
            "Søgade",
            "Sønderbrogade",
            "Sønder Bygade",
            "Sønderdalen",
            "Søndergade",
            "Sønderlund",
            "Søndermarksvej",
            "Sønderskovvej",
            "Søndertorv",
            "Søndervænget",
            "Søren Slibersvej",
            "Søstien",
            "Søvej",
            "Tankegangen",
            "Taulsvej",
            "Teglgaardsvej",
            "Teglværksvej",
            "Telemarksvej",
            "Ternevej",
            "Thorsgade",
            "Thulevej",
            "Thyrasgade",
            "Thyras Vænge",
            "Tidseltoft",
            "Timianvej",
            "Tingbakken",
            "Tingvejen",
            "Tirsbæk Strandvej",
            "Tjørnestræde",
            "Tjørnevej",
            "Toftbovej",
            "Tofteager",
            "Toftegårdsvej",
            "Toftekæret",
            "Toftevej",
            "Toldbodvej",
            "Toldvagten",
            "Torvegade",
            "Torveparken",
            "Tranekærvej",
            "Tranevej",
            "Transitvej",
            "Transportvej",
            "Treenighedsstien",
            "Treschowsgade",
            "Trojavej",
            "Trædballehusvej",
            "Tudvadvej",
            "Tuja Alle",
            "Tulipanvej",
            "Tulipvej",
            "Tvedvej",
            "Tvendevej",
            "Tværhave",
            "Tværvej",
            "Tykmosevej",
            "Tysklandsvej",
            "Tyttebærvej",
            "Tønnesgade",
            "Tårnvej",
            "Udsigten",
            "Uglestien",
            "Uglevej",
            "Uhrskovvej",
            "Ulfsvej",
            "Ulkærvej",
            "Ulvehavevej",
            "Ulvekæden",
            "Ulvevænget",
            "Umanakvej",
            "Uranusvej",
            "Valdemar Poulsensvej",
            "Valdemarsgade",
            "Valløesgade",
            "Valmuevej",
            "Vandværksvej",
            "Vardevej",
            "Ved Anlæget",
            "Ved Banen",
            "Ved Bølgen",
            "Vedelsgade",
            "Ved Hammerværket",
            "Ved Skraaningen",
            "Ved Sønderåen",
            "Ved Vandtaarnet",
            "Ved Vandværket",
            "Vegavej",
            "Vejlevej",
            "Venusvej",
            "Vestavej",
            "Vestbanevej",
            "Vesterbakken",
            "Vesterbrogade",
            "Vesterbyvej",
            "Vestergade",
            "Vesterkant",
            "Vestermarksvej",
            "Vestkæret",
            "Vestparken",
            "Vestre Engvej",
            "Vibestien",
            "Viborg Hovedvej",
            "Viborgvej",
            "Vidtskue Vej",
            "Vilstrupvej",
            "Vindinggård Center",
            "Vindinggårdparken",
            "Vindinggård Ringvej",
            "Vindinghave",
            "Vindingvej",
            "Vingsted Skovvej",
            "Vingstedvej",
            "Vinkelager",
            "Vinkelvej",
            "Violvej",
            "Vissingsgade",
            "Volmersgade",
            "Volmers Plads",
            "Vork Bakker",
            "Vorkvej",
            "Vårfluevej",
            "Willy Sørensens Plads",
            "Windfeld-Hansens Gd",
            "Worsaaesgade",
            "Ydunsgade",
            "Æblehaven",
            "Ærtestien",
            "Ødemarksvej",
            "Ødsted Skovvej",
            "Ømkulevej",
            "Ørnebjergvej",
            "Ørnevej",
            "Ørstedsgade",
            "Ørum Skovvej",
            "Østengårdvej",
            "Østerbrogade",
            "Østerled",
            "Østerlidevej",
            "Øster Starupvej",
            "Østervangsvej",
            "Østjyske Motorvej",
            "Åbrinken",
            "Ådalsvej",
            "Aagade",
            "Aakjærsvej",
            "Aakjærvænget",
            "Åkæret",
            "Åparken",
            "Aasen",
            "Åstræde",
            "Åsvinget",
            "Åvang",
        };
        static List<ModelTestDataOmråde> områder = new List<ModelTestDataOmråde>();
        List<ModelTestDataEjendom> ejendome = new List<ModelTestDataEjendom>();


        public static void OpretData()
        {
            NulstilData();

            LæsOmråder();

            GenererData(1500);

        }

        public static void LæsOmråder()
        {
            SqlDataReader reader = null;
            try
            {
                string sSQL = "SELECT Område.navn, Område.postnr, Postnummer.bynavn, Område.prisfaktor FROM Område, Postnummer WHERE område.postnr = postnummer.postnr";

                SqlCommand command = new SqlCommand(sSQL, ControllerConnection.conn);
                reader = command.ExecuteReader();

                while (reader.Read())
                {
                    områder.Add(new ModelTestDataOmråde(reader.GetString(0), reader.GetInt32(1), reader.GetString(2), (float)reader.GetDouble(3)));                 
                }
            }
            catch (Exception)
            {
            }
            finally
            {
                reader.Close();
            }
        }

        public static void GenererData(int antal)
        {
            int mægler = 1;
            int husejer = 1;
            string område = "";
            int postnr = 0;
            string energimærke = "";
            string startdato = "";
            string salgsdato = "";
            string adresse = "";
            int startpris = 0;
            int nuværendepris = 0;
            int grundareal = 0;
            int kælderareal = 0;
            int boligareal = 0;
            int byggeår = 0;
            int garage = 0;


            for (int i = 0; i < antal; i++)
            {
                Random random = new Random();
                ModelTestDataOmråde modelOmråde = områder[random.Next(0, områder.Count)];

                mægler = random.Next(1, antalMægler + 1);
                område = modelOmråde.Navn;
                husejer = random.Next(1, antalHusejer + 1);
                postnr = modelOmråde.Postnr;
                energimærke = energimærker[random.Next(0, energimærker.Count)];
                adresse = vejnavne[random.Next(0, vejnavne.Count)] + " " + random.Next(0, 200);
                grundareal = random.Next(500, 1200);
                boligareal = random.Next(100, 300);
                byggeår = random.Next(1900, 2019);
                garage = random.Next(0, 2);
                startpris = (int)(boligareal * kvmPris * modelOmråde.PrisFaktor);
                startpris = startpris - (startpris % 100000 + 5000);
                nuværendepris = startpris - prisNedsætelser[random.Next(0, prisNedsætelser.Count)];

                int startår = random.Next(2015, 2019);
                int startmåned = random.Next(1, 13);
                int startdag = random.Next(1, 31);
                if (startmåned == 2)
                {
                    startdag = random.Next(1, 29);
                }
                if (startår == 2018)
                {
                    startmåned = random.Next(1, 6);
                }

                int salgsår = random.Next(2016, 2019);
                int salgsmåned = random.Next(1, 13);
                int salgsdag = random.Next(1, 31);
                if (salgsmåned == 2)
                {
                    salgsdag = random.Next(1, 29);
                }

                startdato = String.Format("{0}-{1:00}-{2:00}", startår, startmåned, startdag);
                salgsdato = String.Format("{0}-{1:00}-{2:00}", salgsår, salgsmåned, salgsdag);
                if (salgsår < startår)
                {
                    salgsdato = "";
                }else if (salgsår == startår && salgsmåned < startmåned)
                {
                    salgsdato = "";
                }
                else if (salgsår == startår && salgsmåned == startmåned && salgsdag < startdag)
                {
                    salgsdato = "";
                }
                else if(salgsår == 2018 && salgsmåned > 5)
                {
                    salgsdato = "";
                }

                int harKælder = random.Next(0, 2);
                if (harKælder == 1)
                {
                    kælderareal = random.Next(10, 50);
                }
                else
                {
                    kælderareal = 0;
                }

                string sSQL = "INSERT INTO Ejendom VALUES(" + mægler + ", " + husejer + ", '" + område + "', " + postnr + ", '" + energimærke + "', '" + startdato + "', '" + salgsdato + "', '" + adresse + "', " + startpris + ", " + nuværendepris + ", " + grundareal + ", " + kælderareal + ", " + boligareal + ", " + byggeår + ", " + garage + ");";
                SqlCommand command = new SqlCommand(sSQL, ControllerConnection.conn);
                command.ExecuteNonQuery();
            }

        }

        public static void NulstilData()
        {
            try
            {
                string sSQL1 = "DROP TABLE Ejendom";

                SqlCommand command1 = new SqlCommand(sSQL1, ControllerConnection.conn);
                command1.ExecuteNonQuery();
            }
            catch (Exception)
            {
            }

            try
            {

                string sSQL = "CREATE TABLE Ejendom(Sagsnr INT PRIMARY KEY IDENTITY(100001,1), MæglerID INT, HusejerID INT, OmrådeNavn VARCHAR(20), Postnr INT, EnergiMærke VARCHAR(10), StartDato VARCHAR(20), SalgsDato VARCHAR(20), Adresse VARCHAR(50), StartPris INT, NuværendePris INT, GrundAreal INT, KælderAreal INT, BoligAreal INT, Byggeår INT, GarageCarport bit)";

                SqlCommand command = new SqlCommand(sSQL, ControllerConnection.conn);
                command.ExecuteNonQuery();
            }
            catch (Exception)
            {

                throw;
            }
        }
        
    }
}
